# Generated by Django 3.2.7 on 2021-10-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id_company',
        ),
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
