# Generated by Django 3.2.7 on 2021-10-07 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myticket', '0003_auto_20211006_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
