# Generated by Django 3.2.7 on 2021-10-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myticket', '0005_auto_20211007_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
